networks:
  dev:
    driver: bridge
services:
  patient-app:
    image: docker.io/library/patientapi:latest
    depends_on:
      - app_db
    container_name: patientapi_services
    ports:
      - '8088:80'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - Connectionstrings__Defaultconnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=Patients; IntegratedSecurity=true;Pooling=true;
      - 'ASPNETCORE_URLS=http://+:80'
    networks:
      - dev
  app_db:
    image: 'postgres:latest'
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Patients
    ports:
      - '5433:5432'
    restart: always
    volumes:
      - 'app_data:/var/lib/postgresql/data'
    networks:
      - dev
volumes:
  app_data: null
